name: 'Render Template'
author: 'Emily McLean'
description: 'Meta composite action to render the pkl action.template.yml.'
runs:
  using: 'composite'
  steps:
    - name: Read current pkl version
      shell: bash
      run: |
        echo "pkl-version=$(cat .github/.pkl-version)" >> ${GITHUB_ENV}
    - name: Render template
      id: render_template
      uses: chuhlomin/render-template@v1
      with:
        template: templates/action.template.yml
        result_path: action.yml
        vars: |
          pkl_version: ${{ env.pkl-version }}