name: Pkl Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1"

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      current-version: ${{ env.PKL_VERSION }}
      latest-version: ${{ steps.pkl-release.outputs.release }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: "develop"
      - name: Get current Pkl version
        run: |
          VER=$(cat .pkl-version)
          echo "PKL_VERSION=$VER" >> $GITHUB_ENV
      - id: pkl-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: apple
          repo: pkl
          excludes: prerelease, draft
  update:
    runs-on: ubuntu-latest
    needs: version
    if: ${{ needs.version.outputs.current-version != needs.version.outputs.latest-version }}
    permissions:
      contents: write
      pull-requests: write
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: "develop"
      - uses: ./render-template
      - run: echo "${{ needs.version.outputs.latest-version }}" > .pkl-version
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "update-pkl/feature/${{ needs.version.outputs.latest-version }}-pkl-lang"
          title: "Update default Pkl from ${{ needs.version.outputs.current-version }} to ${{ needs.version.outputs.latest-version }}"
          assignees: emilymclean
          reviewers: emilymclean
  keep-alive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
