name: Test

on:
  pull_request:
  push:
    branches: [ master, main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./render-template
      - run: cat action.yml
      - run: cat README.md
      - uses: ./
        with:
          input-file: test/example.pkl
          output-file: test/example.json
          format: json
      - run: |
          cat test/example.json